### ISSUE TITLE
Store installation configuration in a separate file

### ISSUE THREAD

**Issue by krlmlr** [roeme/shgit#12]
`./install.sh install` writes two entries in the Git config that contain absolute paths. I'd rather exclude these parts from the global Git config.

For me, the following works:

## `.gitconfig`

```
[include]
	path = .gitconfig.shgit
```

## `.gitconfig.shgit`

```
[shgit]
	quiet-init = true
	prompt-command-mode = stealthy
	verbose-exec = true
	location = /.../git/shgit
[alias]
	sh = !'/.../git/shgit/shgit.sh'
```

Should `./install.sh` default to writing an external file and adding only an include?

**Comment by roeme** [comment]
Yes and no. The fundamental problem here is that we don't have any way of knowing the user's configuration file layout beforehand (some have on big fat file, some have some includes, some have an includedir, some use `$XDG_CONFIG_HOME`...); so we can't really guess where to put the external file, and neither can we present every user a choice fitting to their environment. We could come close, yes, but I'd rather invest development time into other, more important parts of the software. But I'm open to a PR making install.sh more clever.
