### ISSUE TITLE
Support external prompt

### ISSUE THREAD

**Issue by krlmlr** [roeme/shgit#4]
Other projects already solve the prompting problem in a very sophisticated way:

- https://github.com/magicmonty/bash-git-prompt
- https://github.com/arialdomartini/oh-my-git

Can we offer an option to not override the prompt, except perhaps prepending `shgit ` or something else that indicates we are in the shell? We could enable the built-in prompt if `PROMPT_COMMAND` is unset, and that prompt could stay lightweight.

**Comment by roeme** [comment]
Made the prompt behaviour configurable.

**Comment by krlmlr** [comment]
Thanks, works for me.
