### ISSUE TITLE
Echo aliased command before executing it

### ISSUE THREAD

**Issue by krlmlr** [roeme/shgit#8]
My experience from using and teaching `git-sh` suggests that for aliased commands it helps to see the command the alias maps to.

The relevant PR to `git-sh` is here: https://github.com/armano2/git-sh/pull/11/files. Can we port it over?

**Comment by roeme** [comment]
Sure, sounds like an useful functionality. How would one request "teaching mode" (verbose exec)? An envvar comes to mind.

**Comment by krlmlr** [comment]
The "verbose exec" just adds a line to the output, it's always on for me and doesn't really disrupt:

```
$ a .
> git add .
... (output of command, if any)
$ 
```

We can use a git config for this if you prefer.

**Comment by roeme** [comment]
Oops, correct commit is 3afd1e4a411db2.

**Comment by krlmlr** [comment]
Thanks, works as advertised.
